### ISSUE TITLE
Another beta release before the final release

### ISSUE THREAD

**Issue by ming13** [elpassion/mainframer-intellij-plugin#143]
Hey guys. Is it possible to release another beta so we can take a look at the latest changes one more time before the 1.0?

**Comment by OrdonTeam** [comment]
We just did. Yesterday we released new version with changed package name

**Comment by artem-zinnatullin** [comment]
Ah, I guess it'll drop all the settings again? :)

#notcomplainingbutcomplaining

**Comment by ming13** [comment]
Hm, this is strange. I still see 0.3.3 and no update option available :-?

**Comment by pawegio** [comment]
New *Mainframer Integration* plugin in version 0.3.3 with changed package name is [here](https://plugins.jetbrains.com/plugin/9603-mainframer-integration). I'll update readme shortly.

**Comment by ming13** [comment]
Okay, I guess I’m on the latest version then, thanks ;-)
